#!/usr/bin/env python3
"""
Simple concatenation bundler for the refactored planner.
It inlines CommonJS-style modules into a single DataviewJS block.
"""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
DIST_DIR = ROOT / "dist"
OUTPUT_FILE = DIST_DIR / "Kairos_refactored.md"


def collect_modules():
  for path in sorted(SRC_DIR.rglob("*.js")):
    module_id = str(path.relative_to(SRC_DIR)).replace(os.sep, "/")
    yield module_id, path.read_text()


def build_runtime(definitions):
  runtime = """(() => {
const __modules = {};
function __define(id, factory){
  __modules[id] = { factory, exports: {}, initialized: false };
}
function __resolve(from, target){
  if (target.startsWith('.')){
    const fromParts = from.split('/');
    fromParts.pop();
    const targetParts = target.split('/');
    for (const part of targetParts){
      if (part === '.' || part === '') continue;
      if (part === '..') fromParts.pop();
      else fromParts.push(part);
    }
    return fromParts.join('/');
  }
  return target;
}
function __requireModule(id){
  const mod = __modules[id];
  if (!mod) throw new Error('Module not found: ' + id);
  if (!mod.initialized){
    mod.initialized = true;
    mod.factory(mod, mod.exports, createLocalRequire(id));
  }
  return mod.exports;
}
function createLocalRequire(fromId){
  return function(target){
    const resolved = __resolve(fromId, target);
    const withExt = resolved.endsWith('.js') ? resolved : resolved + '.js';
    return __requireModule(withExt);
  };
}

"""
  runtime += "\n".join(definitions)
  runtime += "\nreturn __requireModule('index.js');\n})();"
  return runtime


def main():
  DIST_DIR.mkdir(parents=True, exist_ok=True)
  definitions = []
  for module_id, content in collect_modules():
    definitions.append(
      f"__define('{module_id}', function(module, exports, require) {{\n{content}\n}});"
    )
  bundled_js = build_runtime(definitions)
  with OUTPUT_FILE.open("w", encoding="utf-8") as f:
    f.write("```dataviewjs\n")
    f.write("// Generated by planner_refactor/tools/bundle.py\n")
    f.write(bundled_js)
    f.write("\n```\n")
  print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
  main()
